// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjOFBjutZbxrT7VUB0Ln_y4tWWHZC8kN8',
    appId: '1:377264687395:web:7027155c3fab65a712e496',
    messagingSenderId: '377264687395',
    projectId: 'sunnahsongi',
    authDomain: 'sunnahsongi.firebaseapp.com',
    storageBucket: 'sunnahsongi.appspot.com',
    measurementId: 'G-LT7QBT960V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sXahsmBtcTCCi5PeOo8XVxLBU_ijFNM',
    appId: '1:377264687395:android:d2b783dfeb23ff5c12e496',
    messagingSenderId: '377264687395',
    projectId: 'sunnahsongi',
    storageBucket: 'sunnahsongi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhwwcnKRMOyZtEhcNlCRB2c_UMeZ7qXSs',
    appId: '1:377264687395:ios:d7d57c30418c3c6d12e496',
    messagingSenderId: '377264687395',
    projectId: 'sunnahsongi',
    storageBucket: 'sunnahsongi.appspot.com',
    iosBundleId: 'com.royalcourtbd.sunnahSongi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhwwcnKRMOyZtEhcNlCRB2c_UMeZ7qXSs',
    appId: '1:377264687395:ios:01be5ec0ec5db52e12e496',
    messagingSenderId: '377264687395',
    projectId: 'sunnahsongi',
    storageBucket: 'sunnahsongi.appspot.com',
    iosBundleId: 'com.royalcourtbd.sunnahSongi.RunnerTests',
  );
}
